### ISSUE TITLE
「求助」如何使用 一键配置代理 的脚本？Linux 知识太过小白，非常抱歉。

### ISSUE THREAD

**Issue by faydanube** [bytemain/dotfiles#3]
在 wsl 中，新建 zshrc 并写入代码后不知如何调用……
![image](https://user-images.githubusercontent.com/8817046/103786444-69208000-5077-11eb-9303-0a6df0c0e085.png)

目前是通过每次启动手动赋值 export 代码设置的代理

**Comment by bytemain** [comment]
看起来你的终端应该是 bash

你需要把 proxy 函数写到 .bashrc 中才能在 bash 中调用该函数

比如：
zsh

![image](https://user-images.githubusercontent.com/13938334/103869854-e0045a00-5105-11eb-9914-375fd92a762f.png)

bashrc
![image](https://user-images.githubusercontent.com/13938334/103869846-dd096980-5105-11eb-9d27-a8575ec6da72.png)

**Comment by faydanube** [comment]
非常感謝！
